### ISSUE TITLE
Shutdown reboot buttons in corner not functional

### ISSUE THREAD

**Issue by ryanmusante** [gabretana/simplicity-sddm-theme#1]
Linux: Manjaro
Kernel: 4.15

Neither buttons in the corner have any effect when clicking them with this theme.

**Comment by gabretana** [comment]
Hello, it's very strange I'm using it on two machines with manjaro (kernel 4.14) and both buttons work well, please post your /etc/sddm.conf file content

**Comment by ryanmusante** [comment]
I still use it because it's the most beautiful SDDM theme. Just not sure why those buttons are not functioning for me.
```
# Generated by SDDM Configuration Editor
[Autologin]
Session=/usr/share/xsessions/cinnamon.desktop

[General]
EnableHiDPI=false
Numlock=on

[Theme]
Current=simplicity
DisableAvatarsThreshold=1
FacesDir=/home/ryan/Pictures

[Users]
HideUsers=admin
RememberLastSession=true
RememberLastUser=true
```

**Comment by gabretana** [comment]
I cannot reproduce the issue sorry but I'll continue trying

**Comment by ryanmusante** [comment]
To reboot or shutdown for now, I just ctrl+alt+f to tty to login and issue command as I don't normally need to do it often.

**Comment by gabretana** [comment]
Let's see, post it

**Comment by ryanmusante** [comment]
[Xorg.0.log](https://github.com/gabretana/simplicity-sddm-theme/files/1914129/Xorg.0.log)

**Comment by gabretana** [comment]
For me looks good, but if you can check this https://github.com/sddm/sddm/issues/978, It's something similar

**Comment by ryanmusante** [comment]
I notice that with the new release on AUR, problem is fixed. Do you still recommend I implement the change for SDDM?
